{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redox",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "bayrol_redox_value", "legendFormat": "Redox" },
    { "expr": "bayrol_salt_production_rate", "legendFormat": "Production-Rate" }
   ]
  },
  {
   "title": "Redox",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bayrol_redox_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "bayrol_temperature_value", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "bayrol_ph_value", "legendFormat": "pH" },
    { "expr": "bayrol_ph_dosing_rate", "legendFormat": "Dosing-Rate" }
   ]
  },
  {
   "title": "Salt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "bayrol_salt_value", "legendFormat": "Salt" }
   ]
  }
 ]
}